#!/bin/bash

eval "$(curl -s https://raw.githubusercontent.com/sakkke/afw/main/src/afw)"

afw vars/basic
afw vars/users
afw vars/presets/dotfiles/holman

afw prompts/device

afw deps/basic
afw deps/users
afw deps/presets/dotfiles/holman

afw done
