#!/bin/bash

if [[ -n "${AFW_ENTRYPOINT:-}" ]]; then
  entrypoint="$AFW_ENTRYPOINT"
else
  entrypoint=https://raw.githubusercontent.com/sakkke/afw/main/src
fi

afw() {
  filename="$1"

  if [[ -n "${AFW_ENTRYPOINT:-}" ]]; then
    eval_arg="$(cat "$entrypoint/$filename")"
  else
    eval_arg="$(curl -s "$entrypoint/$filename")"
  fi

  printf '\e[32m%s\e[m\n' "afw> $filename"
  eval "$eval_arg"
}
