#!/bin/bash

eval "$(curl -s https://raw.githubusercontent.com/sakkke/afw/main/lib/afw)"

afw vars/basic
afw vars/users
afw vars/bash/update-bashrc
afw vars/presets/catppuccin/basic

afw prompts/device

afw deps/basic
afw deps/users
afw deps/presets/catppuccin/basic

afw done
