#!/bin/bash

for user in "${AFW_USERS[@]}"; do
  arch-chroot "$AFW_ROOT" git clone https://github.com/holman/dotfiles.git "~$user/.dotfiles"
  arch-chroot "$AFW_ROOT" bash -c 'cd ~/.dotfiles && script/bootstrap'
done
