#!/bin/bash

declare AFW_DEVICE_LABEL="gpt"
declare AFW_EFI_FILE="/GRUB/grubx64.efi"
declare -a AFW_FILESYSTEMS=(
  fat32
  ext4
)
declare AFW_GRUB_BOOTLOADER_ID="GRUB"
declare AFW_HOSTNAME="afw"
declare -a AFW_LOCALE_GEN=(
  "en_US.UTF-8 UTF-8"
)
declare AFW_MOUNT_ENTRYPOINT="/mnt"
declare -a AFW_MOUNTPOINTS=(
  "2:/"
  "1:/boot"
)
declare -a AFW_PACMAN_MIRRORS=(
  'https://mirror.funami.tech/arch/$repo/os/$arch'
)
declare -a AFW_PACSTRAP_PACKAGES=(
  "base"
  "efibootmgr"
  "linux"
  "linux-firmware"
  "networkmanager"
  "grub"
)
declare -a AFW_PARTS=(
  '1 : size=300MiB, type="EFI System"'
  '2 : type="Linux root (x86-64)"'
)
declare -a AFW_PASSWORDS=(
  "root:afw"
)
declare -a AFW_SYSTEMD_SERVICES=(
  "NetworkManager.service"
)
declare AFW_TIMEZONE="UTC"
declare -a AFW_VCONSOLE_CONF=(
  "KEYMAP=us"
)
