#!/bin/bash

set -eu

eval "$(curl -s "https://raw.githubusercontent.com/sakkke/afw/main/afw")"

afw vars/basic

if [[ -z "${AFW_DEVICE:-}" ]]; then
  read -p "AFW_DEVICE=" AFW_DEVICE
fi

afw configs/basic
