#!/bin/bash

DEV=${DEV:-0}

set -e

if ((DEV)); then
  set -ux
  declare AFW_ENTRYPOINT="$(cd "$(dirname "${0}")/../../src" && pwd)"
fi

#declare AFW_DEVICE="/dev/sda"
declare AFW_DEVICE_LABEL="gpt"
declare AFW_EFI_FILE="/GRUB/grubx64.efi"
declare AFW_GRUB_BOOTLOADER_ID="GRUB"
declare AFW_HOSTNAME="afw"
declare -a AFW_LOCALE_GEN=(
  "en_US.UTF-8 UTF-8"
)
declare AFW_MOUNT_ENTRYPOINT="/mnt"
declare -a AFW_MOUNTPOINTS=(
  "2:/"
  "1:/boot"
)
declare -a AFW_PACMAN_MIRRORS=(
  'https://mirror.funami.tech/arch/$repo/os/$arch'
)
declare -a AFW_PACSTRAP_PACKAGES=(
  "base"
  "efibootmgr"
  "linux"
  "linux-firmware"
  "networkmanager"
  "grub"
)
declare -a AFW_PARTS=(
  '1 : size=300MiB, type="EFI System"'
  '2 : type="Linux root (x86-64)"'
)
declare -a AFW_PASSWORDS=(
  "root:afw"
)
declare AFW_TIMEZONE="UTC"
declare -a AFW_VCONSOLE_CONF=(
  "KEYMAP=us"
)

if [[ -z "${AFW_DEVICE:-}" ]]; then
  read -p "AFW_DEVICE=" AFW_DEVICE
fi

eval "$(curl "https://raw.githubusercontent.com/sakkke/afw/main/afw")"

afw update-ntp
afw part
afw mount && trap 'afw umount' "EXIT"
afw pacman/update-mirrorlist
afw pacstrap
afw update-fstab
afw update-timezone
afw update-adjtime
afw update-locale_gen
afw update-locale
afw update-vconsole_conf
afw update-hostname
afw update-passwords
afw grub/install
afw grub/install-grub_cfg
afw grub/fix-bootx64_efi
afw networkmanager/install
