#!/bin/bash

eval "$(curl -s https://raw.githubusercontent.com/sakkke/afw/main/afw)"

afw vars/basic
afw vars/users
afw vars/openbox

afw prompts/device

afw configs/basic
afw configs/users
afw configs/openbox

afw done
