#!/bin/bash

eval "$(curl -s https://raw.githubusercontent.com/sakkke/afw/main/afw)"

afw vars/basic
afw vars/users
afw vars/presets/xmonad

afw prompts/device

afw deps/basic
afw deps/users
afw deps/presets/xmonad

afw done
