#!/bin/bash

eval "$(curl -s https://raw.githubusercontent.com/sakkke/afw/main/lib/afw)"

afw vars/basic
afw vars/users
afw vars/presets/gnome

afw prompts/device

afw deps/basic
afw deps/users
afw deps/presets/gnome

afw done
