#!/bin/bash

eval "$(curl -s https://raw.githubusercontent.com/sakkke/afw/main/lib/afw)"

afw vars/basic
afw vars/presets/openssh

afw prompts/device

afw deps/basic
afw deps/presets/openssh

afw done
