#!/bin/bash

base_url=https://raw.githubusercontent.com/catppuccin/tty/main

case "$AFW_CATPPUCCIN_FLAVOUR" in
  frappe | latte | macchiato | mocha )
    url="$base_url/$AFW_CATPPUCCIN_FLAVOUR.sh"
    ;;

  * )
    url="$base_url/mocha.sh"
esac

mkdir -pv "$AFW_ROOT/usr/share/catppuccin"

curl \
  -o "$AFW_ROOT/usr/share/catppuccin/tty.sh" \
  -s \
  "$url"

printf '%s\n' 'source /usr/share/catppuccin/tty.sh' >> "$AFW_ROOT/etc/skel/.bashrc"
