#!/bin/bash

base_url=https://raw.githubusercontent.com/catppuccin/tty/main

case "$AFW_CATPPUCCIN_FLAVOUR" in
  frappe )
  latte )
  macchiato )
  mocha )
    url="$base_url/$AFW_CATPPUCCIN_FLAVOUR.sh"
    ;;

  * )
    url="$base_url/mocha.sh"
esac

curl \
  --create-dirs \
  -o "$AFW_MOUNT_ENTRYPOINT/usr/share/catppuccin/tty.sh" \
  -s \
  "$url"

chmod a+x "$AFW_MOUNT_ENTRYPOINT/usr/share/catppuccin/tty.sh"
printf '%s\n' 'source /usr/share/catppuccin/tty.sh' >> "$AFW_MOUNT_ENTRYPOINT/etc/skel/.bashrc"
