#!/bin/bash

for part in "${AFW_PARTS[@]}"; do
  if [ "$part" =~ 'type="EFI System"' ]; then
    while read -r part_number _; do
      efi_part_number="$part_number"
    done <<< "$part"
  fi
done

for mountpoint in "${AFW_MOUNTPOINTS[@]}"; do
  while IFS=: read part_number directory; do
    if [ "$part_number" = "$efi_part_number" ]; then
      efi_directory="$directory"
    fi
  done <<< "$mountpoint"
done

arch-chroot "$AFW_MOUNT_ENTRYPOINT" grub-install \
  --bootloader-id="$AFW_GRUB_BOOTLOADER_ID" \
  --efi-directory="$efi_directory" \
  --target=x86_64-efi
