#!/bin/bash

eval "$(curl -s https://raw.githubusercontent.com/sakkke/afw/main/afw)"

afw vars/basic
afw vars/users
afw vars/dotfiles/holman

afw prompts/device

afw configs/basic
afw configs/users
afw configs/dotfiles/holman

afw done
