name: ShellSpec

on:
  push:

jobs:
  build:
    name: shellspec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: sudo apt-get -y install --no-install-recommends kcov

      - name: Install ShellSpec
        run: 'curl -fsSL https://git.io/shellspec | sh -s -- -y'

      - name: shellspec
        run: shellspec --kcov

      - name: Codecov
        uses: codecov/codecov-action@v3
